# -*- coding: utf-8 -*-
"""Sales_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBezrJ4148XvjhtjlHxCFjKHV5pPUkfl
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os

"""
Sales Enablement ROI Analysis - Data Generation Script
Generates synthetic but realistic data for 9K+ sales reps across 12 months
"""

# Set random seed for reproducibility
np.random.seed(42)

# Parameters
total_reps = 9247
trained_reps = int(total_reps * 0.66)  # 66% trained
untrained_reps = total_reps - trained_reps

# Segment distribution
segments = {
    'Enterprise': {'pct': 0.35, 'quota': 850000, 'trained_pct': 0.54},
    'Mid-Market': {'pct': 0.40, 'quota': 450000, 'trained_pct': 0.78},
    'SMB': {'pct': 0.25, 'quota': 200000, 'trained_pct': 0.75}
}

# Programs
programs = ['Sales Skills', 'Product Knowledge', 'Tools Training', 'Soft Skills']

print("Generating Sales Enablement Data...")
print(f"Total Reps: {total_reps:,}")
print(f"Trained: {trained_reps:,} ({100*trained_reps/total_reps:.1f}%)")
print(f"Control: {untrained_reps:,}\n")

# ============ BUILD REP-LEVEL DATA ============
reps_data = []
rep_id = 1

for segment_name, segment_info in segments.items():
    segment_size = int(total_reps * segment_info['pct'])
    segment_trained = int(segment_size * segment_info['trained_pct'])
    segment_untrained = segment_size - segment_trained

    print(f"{segment_name}: {segment_size:,} reps ({segment_trained:,} trained, {segment_untrained:,} control)")

    # Trained reps in this segment
    for i in range(segment_trained):
        trained_date = datetime.now() - timedelta(days=np.random.randint(30, 365))

        # Ramp time: trained reps average 4.2 months (faster)
        ramp_days = int(np.random.normal(126, 28))  # 126 days ≈ 4.2 months
        ramp_days = max(60, min(210, ramp_days))  # Clamp 60-210 days

        reps_data.append({
            'rep_id': rep_id,
            'segment': segment_name,
            'trained': 1,
            'training_date': trained_date.strftime('%Y-%m-%d'),
            'program_1': np.random.choice(programs),
            'program_2': np.random.choice(programs),
            'quota_usd': segment_info['quota'],
            'ramp_days': ramp_days,
        })
        rep_id += 1

    # Untrained reps in this segment
    for i in range(segment_untrained):
        # Ramp time: untrained reps average 5.8 months (slower)
        ramp_days = int(np.random.normal(174, 32))  # 174 days ≈ 5.8 months
        ramp_days = max(90, min(240, ramp_days))  # Clamp 90-240 days

        reps_data.append({
            'rep_id': rep_id,
            'segment': segment_name,
            'trained': 0,
            'training_date': None,
            'program_1': None,
            'program_2': None,
            'quota_usd': segment_info['quota'],
            'ramp_days': ramp_days,
        })
        rep_id += 1

reps_df = pd.DataFrame(reps_data)

# ============ BUILD MONTHLY QUOTA ATTAINMENT DATA ============
monthly_data = []

for month in range(1, 13):
    for _, rep in reps_df.iterrows():
        rep_id = rep['rep_id']
        segment = rep['segment']
        trained = rep['trained']
        ramp_days = rep['ramp_days']
        quota = rep['quota_usd']

        # Quota attainment depends on: training status, month, ramp time
        if trained == 1:
            # Trained reps: ramping up faster
            if month <= ramp_days / 30:  # During ramp period
                attainment = 0.35 + (month / (ramp_days / 30)) * 0.15 + np.random.normal(0, 0.05)
            else:  # After ramp
                attainment = 0.87 + np.random.normal(0, 0.08)
        else:
            # Untrained reps: slower ramp
            if month <= ramp_days / 30:  # During ramp period
                attainment = 0.25 + (month / (ramp_days / 30)) * 0.10 + np.random.normal(0, 0.05)
            else:  # After ramp
                attainment = 0.61 + np.random.normal(0, 0.10)

        # Clamp to 0-100%
        attainment = max(0.0, min(1.0, attainment))

        # Add segment variation
        if segment == 'Enterprise':
            attainment *= 0.92 if trained == 1 else 0.88
        elif segment == 'SMB':
            attainment *= 1.05 if trained == 1 else 0.95

        attainment = max(0.0, min(1.0, attainment))

        # Calculate revenue
        revenue = quota * attainment

        monthly_data.append({
            'rep_id': rep_id,
            'month': month,
            'segment': segment,
            'trained': trained,
            'quota_attainment': round(attainment, 4),
            'revenue': round(revenue, 2),
            'quota': quota,
            'ramp_days': ramp_days,
        })

monthly_df = pd.DataFrame(monthly_data)

# ============ BUILD PROGRAM-LEVEL DATA ============
program_data = [
    {
        'program': 'Sales Skills',
        'participants': int(trained_reps * 0.73),
        'completion_rate': 0.89,
        'avg_score': 84,
        'revenue_impact_millions': 18.2,
        'program_cost_millions': 1.2,
        'quota_lift_pct': 0.26
    },
    {
        'program': 'Product Knowledge',
        'participants': int(trained_reps * 0.68),
        'completion_rate': 0.82,
        'avg_score': 79,
        'revenue_impact_millions': 14.1,
        'program_cost_millions': 0.9,
        'quota_lift_pct': 0.19
    },
    {
        'program': 'Tools Training',
        'participants': int(trained_reps * 0.55),
        'completion_rate': 0.91,
        'avg_score': 87,
        'revenue_impact_millions': 8.3,
        'program_cost_millions': 0.8,
        'quota_lift_pct': 0.12
    },
    {
        'program': 'Soft Skills',
        'participants': int(trained_reps * 0.38),
        'completion_rate': 0.76,
        'avg_score': 75,
        'revenue_impact_millions': 4.6,
        'program_cost_millions': 0.9,
        'quota_lift_pct': 0.07
    },
]

program_df = pd.DataFrame(program_data)

# ============ SAVE TO CSV ============
output_dir = '/home/claude/enablement_data'
os.makedirs(output_dir, exist_ok=True)

reps_df.to_csv(f'{output_dir}/reps.csv', index=False)
monthly_df.to_csv(f'{output_dir}/monthly_attainment.csv', index=False)
program_df.to_csv(f'{output_dir}/programs.csv', index=False)

print(f"\n✓ Data generated successfully!")
print(f"✓ Output files:")
print(f"  - {output_dir}/reps.csv ({len(reps_df):,} rows)")
print(f"  - {output_dir}/monthly_attainment.csv ({len(monthly_df):,} rows)")
print(f"  - {output_dir}/programs.csv ({len(program_df)} programs)")

# ============ PRINT SUMMARY STATISTICS ============
print(f"\n--- SUMMARY STATISTICS ---")
print(f"\nQuota Attainment by Training Status (Months 6-12 avg):")
summary = monthly_df[monthly_df['month'] >= 6].groupby('trained')['quota_attainment'].agg(['mean', 'std'])
summary.index = ['Control (Untrained)', 'Trained']
print(summary.round(3))

print(f"\nRamp Time Statistics (days to 50% quota):")
ramp_summary = reps_df.groupby('trained')['ramp_days'].agg(['mean', 'std', 'min', 'max'])
ramp_summary.index = ['Control (Untrained)', 'Trained']
print(ramp_summary.round(1))

print(f"\nProgram ROI Summary:")
print(program_df[['program', 'participants', 'revenue_impact_millions', 'program_cost_millions']].to_string(index=False))

total_impact = monthly_df[monthly_df['trained'] == 1]['revenue'].sum() - monthly_df[monthly_df['trained'] == 0]['revenue'].sum()
print(f"\nTotal Year 1 Revenue Impact (Trained vs Control): ${total_impact/1e6:.1f}M")
